language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install cmake python-dev libffi-dev

# command to install dependencies
install:
  - "pip install -r requirements-test.txt" 
  - "pip install coveralls"

# command to run tests
script:  nosetests --with-coverage --cover-package=yawt --cover-package=yawtext

after_success: coveralls
