language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements-test.txt" 
  - "pip install coveralls"

# command to run tests
script:  nosetests --with-coverage --cover-package=yawt --cover-package=yawtext --cover-inclusive

after_success: coveralls
