language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install cmake python-dev libffi-dev

# command to install dependencies
install:
  - "pip install -r requirements-full.txt"

# command to run tests
script:  nosetests

