#!/usr/bin/python

activate_this_file = "/path/to/virtualenv/bin/activate_this.py"
execfile(activate_this_file, dict(__file__=activate_this_file))

from yawtext.git import post_commit
post_commit('/path/to/website')
