#!/usr/bin/python

activate_this_file = "/path/to/virtualenv/bin/activate_this.py"
execfile(activate_this_file, dict(__file__=activate_this_file))
 
from yawt.git_hook_utils import git_diff_tree, \
    extract_changed_files, yawt_changed_files

repo_path = '/path/to/website'
git = '/usr/bin/git'

def main():
    diff_tree_out = git_diff_tree(git, repo_path, 'ORIG_HEAD', 'HEAD')
    added_files, modified_files, deleted_files = extract_changed_files(diff_tree_out)
    yawt_changed_files(repo_path, added_files, modified_files, deleted_files)

main()
